language: python
python:
    - "3.4"
    - "3.5"
install:
    - "python setup.py install"
    - "pip install -r requirements/tests.txt"
script:
    - "pytest -v unit_tests"
    - "pytest -v functional_tests"
